name: Daily ARIMAX Forecast

on:
  schedule:
    - cron: '0 22 * * *'  # runs at 22:00 UTC (06:00 Manila)

jobs:
  forecast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas statsmodels matplotlib google-api-python-client google-auth

      - name: Run forecast
        env:
          DRIVE_PATH: ${{ secrets.DRIVE_PATH }}
          CSV_FOLDER: ${{ secrets.CSV_FOLDER }}
          SHEET_ID:   ${{ secrets.SHEET_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python forecast.py
